version: '3.8'

services:
  backend:
    image: frcaballero/lrose-interactive-backend:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: convlstm_backend
    volumes:
      - ./data:/app/data
      - ./model:/app/model # Mount model directory
      - ./backend/output:/app/backend/output # Persist outputs
      - ./frontend/public/mock_data:/app/frontend/public/mock_data # Share generated images with frontend (mock mode or direct access)
    environment:
      - PYTHONUNBUFFERED=1
      - VAPID_PRIVATE_KEY
      - VAPID_CLAIM_EMAIL
      - SECRET_KEY
      - FRONTEND_URL
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: unless-stopped

  frontend:
    image: frcaballero/lrose-interactive-frontend:v1.0.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: convlstm_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000 # Client-side access (browser to backend)
    depends_on:
      - backend
    restart: unless-stopped
